version: '3'

services:

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: tnc_task-cc01
    restart: unless-stopped
    command: bash -c "celery -A tnc_task worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/dev/.django
    volumes:
      - .:/code/
    networks:
      - default

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: tnc_task-cb01
    restart: unless-stopped
    command: bash -c "celery -A tnc_task beat -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/dev/.django
    volumes:
      - .:/code/
    networks:
      - default

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: tnc_task-dc01
    restart: unless-stopped
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./config/env/dev/.django
    ports:
      - 8000:8000
    volumes:
      - ./:/code
      - tnc_task_static_volume:/code/static
      - tnc_task_media_volume:/code/media
    depends_on:
      - postgres
    networks:
      - default

  flower:
    image: mher/flower:0.9.7
    container_name: tnc_task-fc01
    restart: unless-stopped
    command: ["flower", "--broker=redis://redis:6379/0", "--broker_api=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    networks:
      - default

  postgres:
    image: postgres:13.3-buster
    container_name: tnc_task-pc01
    restart: unless-stopped
    env_file:
      - ./config/env/dev/.postgres
    ports:
      - 5434:5432
    volumes:
      - tnc_task_postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  redis:
    image: redis:6.2-buster
    container_name: tnc_task-rc01
    restart: unless-stopped
    volumes:
      - tnc_task_redis_data:/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  tnc_task_postgres_data:
  tnc_task_redis_data:
  tnc_task_static_volume:
  tnc_task_media_volume:
